# Generated by Django 3.1.2 on 2020-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0002_almas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
