# Generated by Django 3.1.2 on 2020-12-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0004_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almas',
            new_name='Person2',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Tom',
        ),
    ]
