# Generated by Django 3.1.2 on 2020-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0006_person3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=20)),
                ('bankChain', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Person2',
        ),
        migrations.DeleteModel(
            name='Person3',
        ),
    ]
