# Generated by Django 3.1.2 on 2020-12-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0007_auto_20201228_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lombard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LombardName', models.CharField(max_length=20)),
                ('LombardChain', models.CharField(max_length=20)),
            ],
        ),
    ]
