# Generated by Django 3.1.5 on 2021-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0008_lombard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarsName', models.CharField(max_length=20)),
                ('CarsChain', models.CharField(max_length=20)),
            ],
        ),
    ]
