# Generated by Django 3.1.5 on 2021-01-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0009_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PeopleName', models.CharField(max_length=20)),
                ('PeopleChain', models.CharField(max_length=20)),
            ],
        ),
    ]
